name: Meta规则集更新

on:
  schedule:
    - cron: '0 */12 * * *'  # 每12小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-meta-rules:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v3
        with:
          path: main-repo

      - name: 设置缓存
        uses: actions/cache@v3
        id: cache-rules
        with:
          path: temp-cache
          key: ${{ runner.os }}-meta-rules-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-meta-rules-

      - name: 克隆Meta规则仓库
        run: |
          mkdir -p temp-repo
          git clone --depth 1 --branch meta https://github.com/MetaCubeX/meta-rules-dat.git temp-repo

      - name: 处理IPv6规则
        run: |
          LIST_DIR="temp-repo/geo/geoip/classical"
          if [ -d "$LIST_DIR" ]; then
            echo "正在转换IPv6规则格式..."
            find "$LIST_DIR" -type f -name "*.list" | while read -r file; do
              sed -i -E 's/^(IP-CIDR,)([^,]*:)/IP-CIDR6,\2/' "$file"
            done
            echo "IPv6规则转换完成"
          else
            echo "目录 $LIST_DIR 不存在，跳过IPv6规则转换"
          fi

      - name: 处理ASN目录
        run: |
          ASN_DIR="temp-repo/asn"
          ASN_CLASSICAL_DIR="$ASN_DIR/classical"
          
          # 确保目录存在
          mkdir -p "$ASN_CLASSICAL_DIR"
          
          echo "开始复制list文件到 $ASN_CLASSICAL_DIR..."
          
          # 复制文件
          find "$ASN_DIR" -maxdepth 1 -type f -name "*.list" | while read -r file; do
            cp "$file" "$ASN_CLASSICAL_DIR"/
          done
          
          echo "文件复制完成"
          
          # 处理文件
          find "$ASN_CLASSICAL_DIR" -type f -name "*.list" | while read -r file; do
            sed -i -E 's/^([^#].*)$/IP-CIDR,\1/' "$file"  # 默认增加 "IP-CIDR,"
            sed -i -E 's/^IP-CIDR,([^,]*:)/IP-CIDR6,\1/' "$file"  # 如果包含 ":"，替换为 "IP-CIDR6,"
          done
          
          echo "ASN目录处理完成"

      - name: 准备输出目录
        run: |
          FINAL_DIR="rule-set/repo"
          if [ -d "$FINAL_DIR" ]; then
            rm -rf "$FINAL_DIR"/*
          else
            mkdir -p "$FINAL_DIR"
          fi

      - name: 复制处理后的文件
        run: |
          echo "正在复制文件到目标目录: rule-set/repo"
          cp -r temp-repo/* rule-set/repo/
          FILE_COUNT=$(find "rule-set/repo" -type f | wc -l)
          echo "下载和更新完成，总文件数: $FILE_COUNT"

      - name: 提交更改
        run: |
          cd main-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add rule-set/repo
          git commit -m "更新Meta规则集 $(date '+%Y-%m-%d %H:%M')" || echo "没有变更需要提交"
          git push 