name: Meta Rules Update

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

jobs:
  Rules-Update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: main-repo
          fetch-depth: 1
          sparse-checkout: |
            rule-set/repo

      - name: Setup Memory FileSystem
        run: |
          echo "::group::Setting up RAM disk"
          sudo mkdir -p /mnt/ramdisk
          sudo mount -t tmpfs -o size=4G tmpfs /mnt/ramdisk
          echo "RAM disk mounted at /mnt/ramdisk with 4GB size"
          mkdir -p /mnt/ramdisk/temp-repo
          mkdir -p /mnt/ramdisk/processed
          echo "::endgroup::"

      - name: Clone Meta Rules Repository
        run: |
          echo "::group::Cloning Meta Rules Repository"
          git clone --depth 1 --branch meta https://github.com/MetaCubeX/meta-rules-dat.git /mnt/ramdisk/temp-repo
          echo "Meta rules repository cloned successfully"
          echo "::endgroup::"

      - name: Process IPv6 Rules
        run: |
          echo "::group::Processing IPv6 Rules"
          LIST_DIR="/mnt/ramdisk/temp-repo/geo/geoip/classical"
          if [ -d "$LIST_DIR" ]; then
            BEFORE_COUNT=$(find "$LIST_DIR" -type f -name "*.list" -print0 | xargs -0 grep -l "IP-CIDR,.*:" | wc -l)
            echo "IPv6 rules files before conversion: $BEFORE_COUNT"
            
            find "$LIST_DIR" -type f -name "*.list" -print0 | xargs -0 -P $(nproc --all) -I{} bash -c "sed -i -E 's/^(IP-CIDR,)([^,]*:)/IP-CIDR6,\2/' {}"
            echo "IPv6 rules conversion completed"
          else
            echo "Directory $LIST_DIR does not exist, skipping IPv6 rules conversion"
          fi
          echo "::endgroup::"

      - name: Process ASN Directory
        run: |
          echo "::group::Processing ASN Directory"
          ASN_DIR="/mnt/ramdisk/temp-repo/asn"
          ASN_CLASSICAL_DIR="$ASN_DIR/classical"
          
          mkdir -p "$ASN_CLASSICAL_DIR"
          
          if [ -d "$ASN_DIR" ]; then
            echo "Copying ASN files..."
            find "$ASN_DIR" -maxdepth 1 -type f -name "*.list" -print0 | xargs -0 -P $(nproc --all) -I{} cp {} "$ASN_CLASSICAL_DIR/"
            FILES_COPIED=$(find "$ASN_CLASSICAL_DIR" -maxdepth 1 -type f -name "*.list" | wc -l)
            echo "ASN files copied: $FILES_COPIED"
            
            echo "Processing ASN files..."
            find "$ASN_CLASSICAL_DIR" -type f -name "*.list" -print0 | xargs -0 -P $(nproc --all) sed -i -E 's/^([^#].*):(.*)$/IP-CIDR6,\1:\2/; s/^([^#IP][^:]*)$/IP-CIDR,\1/'
          else
            echo "ASN directory does not exist"
          fi
          echo "::endgroup::"

      - name: Prepare Output Directory
        run: |
          echo "::group::Preparing Output Directory"
          FINAL_DIR="main-repo/rule-set/repo"
          if [ -d "$FINAL_DIR" ]; then
            rm -rf "$FINAL_DIR"/*
            echo "Output directory cleared"
          else
            mkdir -p "$FINAL_DIR"
            echo "Output directory created"
          fi
          echo "::endgroup::"

      - name: Copy Processed Files
        run: |
          echo "::group::Copying Processed Files"
          TEMP_REPO="/mnt/ramdisk/temp-repo"
          FINAL_DIR="main-repo/rule-set/repo"
          
          find "$TEMP_REPO" -type d | while read -r dir; do
            rel_dir="${dir#$TEMP_REPO/}"
            [ -n "$rel_dir" ] && mkdir -p "$FINAL_DIR/$rel_dir"
          done
          
          echo "Copying files..."
          find "$TEMP_REPO" -type f -print0 | xargs -0 -P $(nproc --all) bash -c '
            for src in "$@"; do
              rel_path="${src#/mnt/ramdisk/temp-repo/}"
              cp "$src" "main-repo/rule-set/repo/$rel_path"
            done
          ' --
          
          echo "Files copied successfully"
          echo "::endgroup::"

      - name: Commit Changes
        run: |
          echo "::group::Committing Changes"
          cd main-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          git config core.compression 9
          git config gc.auto 256
          git config http.postBuffer 524288000
          
          git add -A rule-set/repo
          
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            echo "Committing and pushing changes..."
            git commit -q -m "Chore: Update Meta Rules $(date '+%Y-%m-%d %H:%M')" --no-verify
            git push -q --no-verify
            echo "Changes committed and pushed successfully"
          fi
          echo "::endgroup::"