name: Update Meta Rules

on:
  schedule:
    - cron: '0 7 * * *'  # 每天早上7点运行
  workflow_dispatch:     # 允许手动触发

jobs:
  update-rules:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # 减少克隆深度提高速度
          
      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Setup cache for meta rules
        uses: actions/cache@v3
        id: meta-cache
        with:
          path: /tmp/meta_temp
          key: ${{ runner.os }}-meta-rules-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-meta-rules-
          
      - name: Clone Meta Rules Repository
        if: steps.meta-cache.outputs.cache-hit != 'true'
        run: |
          # 只克隆meta分支并减少深度为1
          git clone --depth 1 --branch meta --single-branch https://github.com/MetaCubeX/meta-rules-dat.git /tmp/meta_temp
          
      - name: Process Rules (Parallel Processing)
        run: |
          # 创建目标目录
          mkdir -p rule-set/repo
          
          # 并行处理IPv6和ASN规则
          {
            # 处理IPv6规则 - 使用awk提高性能
            LIST_DIR="/tmp/meta_temp/geo/geoip/classical"
            if [ -d "$LIST_DIR" ]; then
              find "$LIST_DIR" -type f -name "*.list" -print0 | xargs -0 -P 4 -I{} sh -c '
                awk "{if (/^IP-CIDR,.*:/) {sub(/^IP-CIDR,/,\"IP-CIDR6,\"); print} else {print}}" "{}" > "{}.tmp" && mv "{}.tmp" "{}"
              '
            fi
          } &
          
          {
            # 处理ASN规则 - 优化处理流程
            ASN_DIR="/tmp/meta_temp/asn"
            ASN_CLASSICAL_DIR="$ASN_DIR/classical"
            mkdir -p "$ASN_CLASSICAL_DIR"
            
            # 直接在目标位置处理文件
            find "$ASN_DIR" -maxdepth 1 -type f -name "*.list" -print0 | xargs -0 -P 4 -I{} sh -c '
              FILENAME=$(basename "{}") 
              awk "{if(/^#/) {print} else if(/.*:.*/) {print \"IP-CIDR6,\" \$0} else {print \"IP-CIDR,\" \$0}}" "{}" > "$ASN_CLASSICAL_DIR/$FILENAME"
            '
          } &
          
          # 等待所有并行任务完成
          wait
          
      - name: Update Rules in Repository
        run: |
          # 清空目标目录
          rm -rf rule-set/repo/*
          
          # 使用rsync替代cp提高性能
          rsync -a --delete /tmp/meta_temp/ rule-set/repo/
          
      - name: Commit and Push Changes
        run: |
          git add rule-set/repo/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Chore: Update Meta Rules" && git push) 