name: External Rules Update

on:
  schedule:
    - cron: '0 */8 * * *'  # Every 8 hours (UTC 0:00, 8:00, 16:00)
  workflow_dispatch:  # Allow manual trigger

jobs:
  Rules-Update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Ensure Target Directory
        run: |
          mkdir -p rule-set/external

      - name: Download All Rule Files
        id: download
        shell: bash
        run: |
          echo "::group::Downloading Rule Files"
          
          # Define rule names and URLs using associative array
          declare -A rules=(
            ["DeepSeek"]="https://raw.githubusercontent.com/LOWERTOP/Shadowrocket-First/main/DeepSeek.list"
            ["Talkatone"]="https://raw.githubusercontent.com/mottzz87/crules/main/rule/talkatone.list"
            ["anti-AD"]="https://anti-ad.net/surge.txt"
          )
          
          # Variable to track if any files changed
          changes=false
          
          # Process each rule
          for rule in "${!rules[@]}"; do
            url="${rules[$rule]}"
            
            echo "Downloading $rule.list from $url"
            curl -s -o "rule-set/external/$rule.list.new" "$url"
            
            if [ $? -eq 0 ] && [ -s "rule-set/external/$rule.list.new" ]; then
              if [ -f "rule-set/external/$rule.list" ] && cmp -s "rule-set/external/$rule.list" "rule-set/external/$rule.list.new"; then
                echo "No changes detected for $rule.list"
                rm "rule-set/external/$rule.list.new"
              else
                mv "rule-set/external/$rule.list.new" "rule-set/external/$rule.list"
                echo "$rule.list updated"
                changes=true
              fi
            else
              echo "$rule.list download failed"
              rm -f "rule-set/external/$rule.list.new"
            fi
          done
          
          # Set output variable to indicate if changes were made
          if [ "$changes" = true ]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          else
            echo "changes=false" >> $GITHUB_OUTPUT
          fi
          echo "::endgroup::"

      - name: Commit Changes
        if: steps.download.outputs.changes == 'true'
        run: |
          echo "::group::Committing Changes"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          git add rule-set/external/
          
          TZ=Asia/Shanghai beijing_time=$(date "+%Y-%m-%d %H:%M:%S")
          git commit -m "Update: external rule files (Beijing time: $beijing_time)"
          git push
          echo "Changes committed and pushed"
          echo "::endgroup::"
