name: External Rules Update

on:
  schedule:
    - cron: '0 */8 * * *'  # Every 8 hours (UTC 0:00, 8:00, 16:00)
  workflow_dispatch:  # Allow manual trigger

jobs:
  Rules-Update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rule: [DeepSeek, Talkatone, anti-AD]
        include:
          - rule: DeepSeek
            url: https://raw.githubusercontent.com/LOWERTOP/Shadowrocket-First/main/DeepSeek.list
          - rule: Talkatone
            url: https://raw.githubusercontent.com/mottzz87/crules/main/rule/talkatone.list
          - rule: anti-AD
            url: https://anti-ad.net/surge.txt
      fail-fast: false  # Continue other tasks even if one fails
      max-parallel: 1  # Run one task at a time to avoid git push conflicts
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Ensure Target Directory
        run: |
          mkdir -p rule-set/external

      - name: Download ${{ matrix.rule }} Rule File
        run: |
          echo "::group::Downloading ${{ matrix.rule }}.list"
          curl -s -o rule-set/external/${{ matrix.rule }}.list "${{ matrix.url }}"
          if [ $? -eq 0 ]; then
            echo "${{ matrix.rule }}.list downloaded successfully"
          else
            echo "${{ matrix.rule }}.list download failed"
            exit 1
          fi
          echo "::endgroup::"

      - name: Commit Changes
        run: |
          echo "::group::Committing Changes for ${{ matrix.rule }}"
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
        
          git pull origin main --rebase
        
          git add rule-set/external/${{ matrix.rule }}.list
        
          if git diff --staged --quiet; then
            echo "No changes detected for ${{ matrix.rule }}.list"
          else
            TZ=Asia/Shanghai beijing_time=$(date "+%Y-%m-%d %H:%M:%S")
            git commit -m "Update: ${{ matrix.rule }} rules (Beijing time: $beijing_time)"
            git push
            echo "${{ matrix.rule }}.list changes committed"
          fi
          echo "::endgroup::"
